import type { WorkflowFieldType } from "@/lib/types";

export interface WorkflowTemplateStep {
  name: string;
  description: string | null;
  fieldType: WorkflowFieldType;
  options: string[];
  isMandatory: boolean;
  isStart: boolean;
  posX: number;
  posY: number;
}

export interface WorkflowTemplateBranch {
  fromIndex: number;
  /** null = "cualquier otra respuesta" (rama por defecto del paso) */
  fromOption: string | null;
  /** null = fin del flujo (no hay siguiente paso) */
  toIndex: number | null;
}

export interface WorkflowTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  steps: WorkflowTemplateStep[];
  branches: WorkflowTemplateBranch[];
}

export const WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  {
    id: "bienvenida",
    name: "Bienvenida a nuevo cliente",
    description: "Confirma identidad, presenta el servicio y resuelve dudas iniciales.",
    icon: "👋",
    steps: [
      {
        name: "Confirmar identidad",
        description: "Verifica que hablas con el titular de la cuenta.",
        fieldType: "single_choice",
        options: ["Es el titular", "No se encuentra", "Número equivocado"],
        isMandatory: true,
        isStart: true,
        posX: 40,
        posY: 80,
      },
      {
        name: "Presentar motivo de la llamada",
        description: "Explica que la llamada es para dar la bienvenida y revisar el servicio contratado.",
        fieldType: "text",
        options: [],
        isMandatory: true,
        isStart: false,
        posX: 380,
        posY: 80,
      },
      {
        name: "¿Tiene dudas sobre el servicio?",
        description: null,
        fieldType: "single_choice",
        options: ["Sí tiene dudas", "No tiene dudas"],
        isMandatory: true,
        isStart: false,
        posX: 720,
        posY: 80,
      },
      {
        name: "Resolver dudas del cliente",
        description: "Responde las consultas puntuales antes de cerrar.",
        fieldType: "text",
        options: [],
        isMandatory: true,
        isStart: false,
        posX: 1060,
        posY: -60,
      },
      {
        name: "Cierre exitoso",
        description: "Agradece y cierra la llamada de bienvenida.",
        fieldType: "text",
        options: [],
        isMandatory: false,
        isStart: false,
        posX: 1400,
        posY: 80,
      },
      {
        name: "Agendar reintento",
        description: "El cliente no se encontraba, agenda un nuevo horario de contacto.",
        fieldType: "combobox",
        options: ["Mañana", "Tarde", "Noche"],
        isMandatory: true,
        isStart: false,
        posX: 380,
        posY: 320,
      },
      {
        name: "Cierre - número equivocado",
        description: null,
        fieldType: "text",
        options: [],
        isMandatory: false,
        isStart: false,
        posX: 380,
        posY: 520,
      },
    ],
    branches: [
      { fromIndex: 0, fromOption: "Es el titular", toIndex: 1 },
      { fromIndex: 0, fromOption: "No se encuentra", toIndex: 5 },
      { fromIndex: 0, fromOption: "Número equivocado", toIndex: 6 },
      { fromIndex: 1, fromOption: null, toIndex: 2 },
      { fromIndex: 2, fromOption: "Sí tiene dudas", toIndex: 3 },
      { fromIndex: 2, fromOption: "No tiene dudas", toIndex: 4 },
      { fromIndex: 3, fromOption: null, toIndex: 4 },
      { fromIndex: 4, fromOption: null, toIndex: null },
      { fromIndex: 5, fromOption: null, toIndex: null },
      { fromIndex: 6, fromOption: null, toIndex: null },
    ],
  },

  {
    id: "encuesta",
    name: "Encuesta de satisfacción",
    description: "Mide satisfacción general y profundiza si hay una mala experiencia.",
    icon: "📋",
    steps: [
      {
        name: "Confirmar disponibilidad",
        description: "Pregunta si el cliente tiene unos minutos para responder la encuesta.",
        fieldType: "single_choice",
        options: ["Tiene tiempo ahora", "No tiene tiempo"],
        isMandatory: true,
        isStart: true,
        posX: 40,
        posY: 80,
      },
      {
        name: "Pregunta de satisfacción general",
        description: "¿Qué tan satisfecho está con nuestro servicio?",
        fieldType: "single_choice",
        options: ["Muy satisfecho", "Satisfecho", "Insatisfecho", "Muy insatisfecho"],
        isMandatory: true,
        isStart: false,
        posX: 380,
        posY: 80,
      },
      {
        name: "Preguntar motivo de insatisfacción",
        description: "Indaga qué generó la mala experiencia.",
        fieldType: "text",
        options: [],
        isMandatory: true,
        isStart: false,
        posX: 720,
        posY: 220,
      },
      {
        name: "Agradecer y cerrar encuesta",
        description: null,
        fieldType: "text",
        options: [],
        isMandatory: false,
        isStart: false,
        posX: 1060,
        posY: 80,
      },
      {
        name: "Agendar nueva llamada",
        description: "El cliente no tenía tiempo, ofrece otro horario.",
        fieldType: "combobox",
        options: ["Mañana", "Tarde", "Noche"],
        isMandatory: true,
        isStart: false,
        posX: 380,
        posY: 320,
      },
    ],
    branches: [
      { fromIndex: 0, fromOption: "Tiene tiempo ahora", toIndex: 1 },
      { fromIndex: 0, fromOption: "No tiene tiempo", toIndex: 4 },
      { fromIndex: 1, fromOption: "Muy satisfecho", toIndex: 3 },
      { fromIndex: 1, fromOption: "Satisfecho", toIndex: 3 },
      { fromIndex: 1, fromOption: "Insatisfecho", toIndex: 2 },
      { fromIndex: 1, fromOption: "Muy insatisfecho", toIndex: 2 },
      { fromIndex: 2, fromOption: null, toIndex: 3 },
      { fromIndex: 3, fromOption: null, toIndex: null },
      { fromIndex: 4, fromOption: null, toIndex: null },
    ],
  },

  {
    id: "seguros",
    name: "Venta de seguros",
    description: "Levanta interés, cotiza y cierra la venta o agenda seguimiento.",
    icon: "🛡️",
    steps: [
      {
        name: "Confirmar interés inicial",
        description: null,
        fieldType: "single_choice",
        options: ["Interesado", "No interesado", "Quiere más información"],
        isMandatory: true,
        isStart: true,
        posX: 40,
        posY: 160,
      },
      {
        name: "Levantar necesidad (tipo de seguro)",
        description: "¿Qué tipo de seguro le interesa?",
        fieldType: "combobox",
        options: ["Seguro de vida", "Seguro de salud", "Seguro automotriz", "Seguro de hogar"],
        isMandatory: true,
        isStart: false,
        posX: 380,
        posY: 80,
      },
      {
        name: "Enviar información por correo o WhatsApp",
        description: null,
        fieldType: "text",
        options: [],
        isMandatory: false,
        isStart: false,
        posX: 380,
        posY: 320,
      },
      {
        name: "Cierre - no interesado",
        description: null,
        fieldType: "text",
        options: [],
        isMandatory: false,
        isStart: false,
        posX: 380,
        posY: 520,
      },
      {
        name: "Presentar cotización",
        description: "Presenta el plan y el valor mensual estimado.",
        fieldType: "text",
        options: [],
        isMandatory: true,
        isStart: false,
        posX: 720,
        posY: 80,
      },
      {
        name: "¿Acepta la propuesta?",
        description: null,
        fieldType: "single_choice",
        options: ["Acepta", "Lo va a pensar", "Rechaza"],
        isMandatory: true,
        isStart: false,
        posX: 1060,
        posY: 80,
      },
      {
        name: "Cierre - venta concretada",
        description: "Registrar datos de pago y confirmar póliza.",
        fieldType: "text",
        options: [],
        isMandatory: true,
        isStart: false,
        posX: 1400,
        posY: -80,
      },
      {
        name: "Agendar seguimiento",
        description: null,
        fieldType: "combobox",
        options: ["3 días", "1 semana", "2 semanas"],
        isMandatory: true,
        isStart: false,
        posX: 1400,
        posY: 80,
      },
      {
        name: "Cierre - rechazo",
        description: null,
        fieldType: "text",
        options: [],
        isMandatory: false,
        isStart: false,
        posX: 1400,
        posY: 260,
      },
    ],
    branches: [
      { fromIndex: 0, fromOption: "Interesado", toIndex: 1 },
      { fromIndex: 0, fromOption: "Quiere más información", toIndex: 2 },
      { fromIndex: 0, fromOption: "No interesado", toIndex: 3 },
      { fromIndex: 1, fromOption: null, toIndex: 4 },
      { fromIndex: 4, fromOption: null, toIndex: 5 },
      { fromIndex: 5, fromOption: "Acepta", toIndex: 6 },
      { fromIndex: 5, fromOption: "Lo va a pensar", toIndex: 7 },
      { fromIndex: 5, fromOption: "Rechaza", toIndex: 8 },
      { fromIndex: 2, fromOption: null, toIndex: null },
      { fromIndex: 3, fromOption: null, toIndex: null },
      { fromIndex: 6, fromOption: null, toIndex: null },
      { fromIndex: 7, fromOption: null, toIndex: null },
      { fromIndex: 8, fromOption: null, toIndex: null },
    ],
  },

  {
    id: "cobranza",
    name: "Cobranza - recordatorio de pago",
    description: "Informa la deuda, evalúa capacidad de pago y registra el compromiso.",
    icon: "💳",
    steps: [
      {
        name: "Confirmar identidad del titular",
        description: null,
        fieldType: "single_choice",
        options: ["Es el titular", "No se encuentra", "Número equivocado"],
        isMandatory: true,
        isStart: true,
        posX: 40,
        posY: 160,
      },
      {
        name: "Informar deuda pendiente",
        description: "Indica el monto adeudado y la fecha de vencimiento.",
        fieldType: "text",
        options: [],
        isMandatory: true,
        isStart: false,
        posX: 380,
        posY: 80,
      },
      {
        name: "Agendar reintento",
        description: null,
        fieldType: "combobox",
        options: ["Mañana", "Tarde", "Noche"],
        isMandatory: true,
        isStart: false,
        posX: 380,
        posY: 320,
      },
      {
        name: "Cierre - número equivocado",
        description: null,
        fieldType: "text",
        options: [],
        isMandatory: false,
        isStart: false,
        posX: 380,
        posY: 520,
      },
      {
        name: "¿Puede pagar hoy?",
        description: null,
        fieldType: "single_choice",
        options: ["Sí, paga hoy", "No puede pagar", "Necesita más plazo"],
        isMandatory: true,
        isStart: false,
        posX: 720,
        posY: 80,
      },
      {
        name: "Registrar promesa de pago",
        description: null,
        fieldType: "text",
        options: [],
        isMandatory: true,
        isStart: false,
        posX: 1060,
        posY: -80,
      },
      {
        name: "Ofrecer plan de pago / convenio",
        description: null,
        fieldType: "text",
        options: [],
        isMandatory: true,
        isStart: false,
        posX: 1060,
        posY: 80,
      },
      {
        name: "Derivar a cobranza judicial / cierre",
        description: null,
        fieldType: "text",
        options: [],
        isMandatory: false,
        isStart: false,
        posX: 1060,
        posY: 260,
      },
    ],
    branches: [
      { fromIndex: 0, fromOption: "Es el titular", toIndex: 1 },
      { fromIndex: 0, fromOption: "No se encuentra", toIndex: 2 },
      { fromIndex: 0, fromOption: "Número equivocado", toIndex: 3 },
      { fromIndex: 1, fromOption: null, toIndex: 4 },
      { fromIndex: 4, fromOption: "Sí, paga hoy", toIndex: 5 },
      { fromIndex: 4, fromOption: "Necesita más plazo", toIndex: 6 },
      { fromIndex: 4, fromOption: "No puede pagar", toIndex: 7 },
      { fromIndex: 2, fromOption: null, toIndex: null },
      { fromIndex: 3, fromOption: null, toIndex: null },
      { fromIndex: 5, fromOption: null, toIndex: null },
      { fromIndex: 6, fromOption: null, toIndex: null },
      { fromIndex: 7, fromOption: null, toIndex: null },
    ],
  },

  {
    id: "retencion",
    name: "Renovación y retención de clientes",
    description: "Informa el vencimiento, ofrece retención y registra la decisión final.",
    icon: "🔁",
    steps: [
      {
        name: "Confirmar identidad",
        description: null,
        fieldType: "single_choice",
        options: ["Es el titular", "No se encuentra"],
        isMandatory: true,
        isStart: true,
        posX: 40,
        posY: 80,
      },
      {
        name: "Informar próximo vencimiento del servicio",
        description: null,
        fieldType: "text",
        options: [],
        isMandatory: true,
        isStart: false,
        posX: 380,
        posY: 80,
      },
      {
        name: "Agendar reintento",
        description: null,
        fieldType: "combobox",
        options: ["Mañana", "Tarde", "Noche"],
        isMandatory: true,
        isStart: false,
        posX: 380,
        posY: 320,
      },
      {
        name: "¿Desea renovar?",
        description: null,
        fieldType: "single_choice",
        options: ["Renueva", "No renueva", "Quiere mejor oferta"],
        isMandatory: true,
        isStart: false,
        posX: 720,
        posY: 80,
      },
      {
        name: "Confirmar renovación y datos de pago",
        description: null,
        fieldType: "text",
        options: [],
        isMandatory: true,
        isStart: false,
        posX: 1060,
        posY: -80,
      },
      {
        name: "Ofrecer descuento de retención",
        description: null,
        fieldType: "text",
        options: [],
        isMandatory: true,
        isStart: false,
        posX: 1060,
        posY: 80,
      },
      {
        name: "Registrar motivo de cancelación",
        description: null,
        fieldType: "text",
        options: [],
        isMandatory: false,
        isStart: false,
        posX: 1060,
        posY: 260,
      },
    ],
    branches: [
      { fromIndex: 0, fromOption: "Es el titular", toIndex: 1 },
      { fromIndex: 0, fromOption: "No se encuentra", toIndex: 2 },
      { fromIndex: 1, fromOption: null, toIndex: 3 },
      { fromIndex: 3, fromOption: "Renueva", toIndex: 4 },
      { fromIndex: 3, fromOption: "Quiere mejor oferta", toIndex: 5 },
      { fromIndex: 3, fromOption: "No renueva", toIndex: 6 },
      { fromIndex: 2, fromOption: null, toIndex: null },
      { fromIndex: 4, fromOption: null, toIndex: null },
      { fromIndex: 5, fromOption: null, toIndex: null },
      { fromIndex: 6, fromOption: null, toIndex: null },
    ],
  },
];
