-- Atlas Vendedor: el agente que contesta a quien responde.
--
-- Hoy alguien contesta "cuéntame más" a las 22:40 y esa respuesta espera a que
-- alguien abra el correo. El interés se enfría en horas.
--
-- Arranca en modo borrador: escribe y espera aprobación. Cuando su forma de
-- escribir convenza, se cambia `modo` a 'autonomo' y contesta solo. La
-- constitución vive en la base, no en el código: cambiar cómo habla el agente
-- no puede exigir un despliegue.
--
-- El cuerpo aplicado está en las funciones; este archivo deja el esquema para
-- que la próxima base nazca igual. Ver también 20260918150100.
